defaults:
  - _self_
  - augmentations: symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

name: "vicreg-miniimagenet"
method: "vicreg"
backbone:
  name: "resnet10"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0
  gamma: 0.0001
data:
  dataset: miniimagenet
  train_path: "../../data/miniImagenet"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.3
  weight_decay: 1e-4
  exclude_bias_n_norm_wd: True
  kwargs:
    clip_lr: False
    eta: 0.001
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 10
auto_resume:
  enabled: True

max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed

